"""added coords to rest, gas, and hotel models

Revision ID: 17a81015848f
Revises: 780bd4cbc593
Create Date: 2020-11-29 20:05:07.736274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17a81015848f'
down_revision = '780bd4cbc593'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gas_stations', sa.Column('coordinates', sa.String(length=50), nullable=True))
    op.add_column('hotels', sa.Column('coordinates', sa.String(length=50), nullable=True))
    op.add_column('restaurants', sa.Column('coordinates', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'coordinates')
    op.drop_column('hotels', 'coordinates')
    op.drop_column('gas_stations', 'coordinates')
    # ### end Alembic commands ###
