"""updated rest, gas, hotel, and stop models

Revision ID: ab5d35324a38
Revises: 232db319efde
Create Date: 2020-11-29 02:16:16.863606

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ab5d35324a38'
down_revision = '232db319efde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gas_stations', sa.Column('city', sa.String(length=50), nullable=True))
    op.add_column('gas_stations', sa.Column('img_url', sa.String(length=255), nullable=True))
    op.add_column('gas_stations', sa.Column('phone_num', sa.String(length=15), nullable=True))
    op.add_column('gas_stations', sa.Column('state', sa.String(length=2), nullable=True))
    op.add_column('gas_stations', sa.Column('street_address', sa.String(length=100), nullable=True))
    op.add_column('gas_stations', sa.Column('zip_code', sa.Integer(), nullable=True))
    op.add_column('hotels', sa.Column('city', sa.String(length=50), nullable=True))
    op.add_column('hotels', sa.Column('img_url', sa.String(length=255), nullable=True))
    op.add_column('hotels', sa.Column('phone_num', sa.String(length=15), nullable=True))
    op.add_column('hotels', sa.Column('state', sa.String(length=2), nullable=True))
    op.add_column('hotels', sa.Column('street_address', sa.String(length=100), nullable=True))
    op.add_column('hotels', sa.Column('zip_code', sa.String(length=10), nullable=True))
    op.add_column('restaurants', sa.Column('city', sa.String(length=50), nullable=True))
    op.add_column('restaurants', sa.Column('img_url', sa.String(length=255), nullable=True))
    op.add_column('restaurants', sa.Column('phone_num', sa.String(length=15), nullable=True))
    op.add_column('restaurants', sa.Column('state', sa.String(length=2), nullable=True))
    op.add_column('restaurants', sa.Column('street_address', sa.String(length=100), nullable=True))
    op.add_column('restaurants', sa.Column('zip_code', sa.String(length=10), nullable=True))
    op.add_column('stops', sa.Column('time', sa.DateTime(), nullable=True))
    op.alter_column('trips', 'end_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('trips', 'start_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trips', 'start_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('trips', 'end_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('stops', 'time')
    op.drop_column('restaurants', 'zip_code')
    op.drop_column('restaurants', 'street_address')
    op.drop_column('restaurants', 'state')
    op.drop_column('restaurants', 'phone_num')
    op.drop_column('restaurants', 'img_url')
    op.drop_column('restaurants', 'city')
    op.drop_column('hotels', 'zip_code')
    op.drop_column('hotels', 'street_address')
    op.drop_column('hotels', 'state')
    op.drop_column('hotels', 'phone_num')
    op.drop_column('hotels', 'img_url')
    op.drop_column('hotels', 'city')
    op.drop_column('gas_stations', 'zip_code')
    op.drop_column('gas_stations', 'street_address')
    op.drop_column('gas_stations', 'state')
    op.drop_column('gas_stations', 'phone_num')
    op.drop_column('gas_stations', 'img_url')
    op.drop_column('gas_stations', 'city')
    # ### end Alembic commands ###
