"""added mpg to cars again

Revision ID: 780bd4cbc593
Revises: ab5d35324a38
Create Date: 2020-11-29 14:11:01.965261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '780bd4cbc593'
down_revision = 'ab5d35324a38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('mpg', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cars', 'mpg')
    # ### end Alembic commands ###
