"""added end_iso to Trip

Revision ID: d07138ae000a
Revises: 331ffc10ca29
Create Date: 2020-12-26 15:04:26.853872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd07138ae000a'
down_revision = '331ffc10ca29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('end_iso', sa.String(length=35), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'end_iso')
    # ### end Alembic commands ###
