"""had to remove img_url in order for changes to be discovered

Revision ID: ed888a5f75e7
Revises: d07138ae000a
Create Date: 2020-12-26 16:16:34.038961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed888a5f75e7'
down_revision = 'd07138ae000a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gas_stations', 'img_url')
    op.drop_column('hotels', 'img_url')
    op.drop_column('restaurants', 'img_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('img_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('hotels', sa.Column('img_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('gas_stations', sa.Column('img_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
