"""changed mpg to miles_to_refuel in Cars Model

Revision ID: 232db319efde
Revises: ee2d7028c2c6
Create Date: 2020-11-28 13:28:59.474612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '232db319efde'
down_revision = 'ee2d7028c2c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('miles_to_refuel', sa.Integer(), nullable=False))
    op.drop_column('cars', 'mpg')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('mpg', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('cars', 'miles_to_refuel')
    # ### end Alembic commands ###
