"""added directions column to trips

Revision ID: ee2d7028c2c6
Revises: 0c77ff427e5e
Create Date: 2020-11-27 17:03:54.103253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee2d7028c2c6'
down_revision = '0c77ff427e5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('directions', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'directions')
    # ### end Alembic commands ###
