"""added img_url back in as Text data type

Revision ID: 9f2177eaad9f
Revises: ed888a5f75e7
Create Date: 2020-12-26 16:17:26.755812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f2177eaad9f'
down_revision = 'ed888a5f75e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gas_stations', sa.Column('img_url', sa.Text(), nullable=True))
    op.add_column('hotels', sa.Column('img_url', sa.Text(), nullable=True))
    op.add_column('restaurants', sa.Column('img_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'img_url')
    op.drop_column('hotels', 'img_url')
    op.drop_column('gas_stations', 'img_url')
    # ### end Alembic commands ###
