"""cleaned redundent columns out of Trip Model

Revision ID: 768ad09a2fd0
Revises: c0863d53cdeb
Create Date: 2020-12-19 21:51:29.945374

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '768ad09a2fd0'
down_revision = 'c0863d53cdeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'stop_time_limit')
    op.drop_column('trips', 'daily_time_limit')
    op.drop_column('trips', 'start_time')
    op.drop_column('trips', 'start_location')
    op.drop_column('trips', 'end_time')
    op.drop_column('trips', 'end_location')
    op.drop_column('trips', 'toll')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('toll', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('trips', sa.Column('end_location', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('trips', sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('trips', sa.Column('start_location', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('trips', sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('trips', sa.Column('daily_time_limit', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('trips', sa.Column('stop_time_limit', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
