"""made some columns nullable on the Trip table

Revision ID: c0863d53cdeb
Revises: 17a81015848f
Create Date: 2020-11-30 19:53:13.134588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0863d53cdeb'
down_revision = '17a81015848f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trips', 'car_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('trips', 'daily_time_limit',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('trips', 'stop_time_limit',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('trips', 'toll',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trips', 'toll',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('trips', 'stop_time_limit',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('trips', 'daily_time_limit',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('trips', 'car_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
