"""added trip_url to Trip model

Revision ID: ea2279853561
Revises: 9f2177eaad9f
Create Date: 2021-01-13 20:53:45.690460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea2279853561'
down_revision = '9f2177eaad9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('trip_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'trip_url')
    # ### end Alembic commands ###
